-- B-100 · Migration 001: catálogo AliExpress, importador, clicks e administração.
-- Executar no SQL Editor do projeto Supabase antes de ativar a área admin.

alter table products
  add column if not exists aliexpress_id text,
  add column if not exists title text,
  add column if not exists affiliate_url text,
  add column if not exists original_price numeric,
  add column if not exists discount text,
  add column if not exists currency text,
  add column if not exists sales_180_days integer,
  add column if not exists positive_feedback numeric,
  add column if not exists commission_rate numeric,
  add column if not exists estimated_commission numeric,
  add column if not exists coupon_name text,
  add column if not exists coupon_value numeric,
  add column if not exists coupon_quantity integer,
  add column if not exists coupon_minimum_spend numeric,
  add column if not exists coupon_start_time timestamptz,
  add column if not exists coupon_end_time timestamptz,
  add column if not exists status text default 'published',
  add column if not exists updated_at timestamptz default now();

alter table products drop constraint if exists products_status_check;
alter table products add constraint products_status_check check (status in ('published', 'over_limit', 'invalid'));
create unique index if not exists products_aliexpress_id_key on products (aliexpress_id) where aliexpress_id is not null;

create table if not exists admins (user_id uuid primary key references auth.users (id) on delete cascade, created_at timestamptz default now());
create table if not exists b100_clicks (id bigint generated by default as identity primary key, product_id bigint not null, created_at timestamptz default now());

create or replace function is_admin() returns boolean language sql security definer set search_path = public as $$
  select exists (select 1 from admins where user_id = auth.uid());
$$;

alter table products enable row level security;
drop policy if exists "public_select_published" on products;
create policy "public_select_published" on products for select using (status = 'published');
drop policy if exists "admin_select_all" on products;
create policy "admin_select_all" on products for select using (is_admin());
drop policy if exists "admin_insert" on products;
create policy "admin_insert" on products for insert with check (is_admin());
drop policy if exists "admin_update" on products;
create policy "admin_update" on products for update using (is_admin()) with check (is_admin());
drop policy if exists "admin_delete" on products;
create policy "admin_delete" on products for delete using (is_admin());

alter table b100_clicks enable row level security;
drop policy if exists "anyone_can_insert_b100_click" on b100_clicks;
create policy "anyone_can_insert_b100_click" on b100_clicks for insert with check (true);
drop policy if exists "admin_select_b100_clicks" on b100_clicks;
create policy "admin_select_b100_clicks" on b100_clicks for select using (is_admin());

alter table admins enable row level security;
drop policy if exists "admin_select_admins" on admins;
create policy "admin_select_admins" on admins for select using (is_admin());

-- Criar o primeiro utilizador no Supabase Auth e, depois, executar:
-- insert into admins (user_id) values ('COLA_AQUI_O_USER_ID_DO_AUTH');
